/** Autogenerated Main.cpp. */

// =============================| Include only the DSP files  |=============================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// =======================| Now we can add the rest of the codebase |=======================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// ===================================| Project Factory |===================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations -------------------------------------------------------------
		
		registerPolyNode<project::Env2<1>, project::Env2<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::modtest1<1>, project::modtest1<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::xnode<1>, project::xnode<NUM_POLYPHONIC_VOICES>>();
		registerDataNode<project::ArrangeNew_networkdata>();
		registerDataNode<project::bbdish_networkdata>();
		registerDataNode<project::dlay_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::Env_networkdata>();
		registerDataNode<project::Env3_networkdata>();
		registerDataNode<project::Env4_networkdata>();
		registerDataNode<project::f_networkdata>();
		registerDataNode<project::Fausted_networkdata>();
		registerDataNode<project::fx_networkdata>();
		registerDataNode<project::ga_networkdata>();
		registerDataNode<project::GainMod_networkdata>();
		registerDataNode<project::gmt_networkdata>();
		registerDataNode<project::harmnode_networkdata>();
		registerDataNode<project::harmo_networkdata>();
		registerDataNode<project::Htwentyfour_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::mod_networkdata>();
		registerDataNode<project::modconnet_networkdata>();
		registerDataNode<project::pb_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::QuadCho_networkdata>();
		registerDataNode<project::TRACK_LFO_networkdata>();
		registerDataNode<project::Xarrange_networkdata>();
		registerDataNode<project::xnodeCycle_networkdata>();
		registerDataNode<project::xnodeUser_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


