/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

<<<<<<< HEAD
// Include third party header files ----------------

#include "BPF.h"
#include "Comb.h"
#include "granular.h"
#include "HPF.h"
#include "klp2.h"
#include "LPF.h"
#include "OBLP.h"
#include "RevDel.h"

=======
>>>>>>> parent of 416899d (s&h gate)
// Include compiled network files ------------------

#include "bbdish_networkdata.h"
#include "dlay.h"
#include "Env2_networkdata.h"
#include "Env3_networkdata.h"
#include "Env4_networkdata.h"
#include "Env_networkdata.h"
#include "harmnode_networkdata.h"
#include "harmo_networkdata.h"
#include "Htwentyfour_networkdata.h"
#include "modtest1.h"
#include "mod_networkdata.h"
<<<<<<< HEAD
=======
#include "pb_networkdata.h"
#include "QuadCho_networkdata.h"
>>>>>>> d2
#include "TRACK_LFO_networkdata.h"
#include "Xarrange.h"
#include "xnode.h"
#include "xnodeUser_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

