/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include compiled network files ------------------

#include "ArrangeNew.h"
#include "bbdish_networkdata.h"
#include "dlay_networkdata.h"
#include "Env2.h"
#include "Env3_networkdata.h"
#include "Env4_networkdata.h"
#include "Env_networkdata.h"
#include "Fausted_networkdata.h"
#include "fx.h"
#include "f_networkdata.h"
#include "GainMod_networkdata.h"
#include "ga_networkdata.h"
#include "harmnode_networkdata.h"
#include "harmo_networkdata.h"
#include "Htwentyfour_networkdata.h"
#include "modconnet_networkdata.h"
#include "modtest1.h"
#include "mod_networkdata.h"
#include "pb_networkdata.h"
#include "QuadCho_networkdata.h"
#include "TRACK_LFO_networkdata.h"
#include "Xarrange_networkdata.h"
#include "xnode.h"
#include "xnodeCycle_networkdata.h"
#include "xnodeUser_networkdata.h"
#include "_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

