namespace project
{

struct p2_networkdata: public scriptnode::dll::InterpretedNetworkData
{
	String getId() const override
	{
		return "p2";
	}
	bool isModNode() const override
	{
		return false;
	}
	String getNetworkData() const override
	{
		return "705.nT6K8Cl0GzaE.XLWaUB7tpFOSQT6iOPFam1TCOaskce8I5FxPQRR3IwgkNO+NuqjY.2+NA.T.DE.XvfvtkNy1GChvqwjmT5veFaBQiW6Y+DumiY8J8xRQl0uabWcrRmVrMknghv.ds8oaX+hVBcdMF09Xtc0mhluVezQWXiWGQB70YvulrOQN9BedsyUmWz1mlwbq8gzQyX+9XJNudhRJMYE4HZBy80GBzEKMy8XuVYhgQcV4qWfGzvYgNC1WqfgiMTKvBb5M.1vd10l3IEMOlLeaad6dny.ONQXoyKvGn5iM..Ydp8YtGYPutd9xAI7AJaXimYkrgcKV3dnaVuazHy7LxFud0dHsCji6rWqgAH2LmzPKcRmk8nmZWHTR1ufmVLqbY+jtiR2X3KX2VrPQ127JfEz8EKES9esKYrxZxgkkTTFkdrhRxIGSUUwpnnnoDdsFOyUKcPJiVSxnTgXTfmGAUxFbIGUTQRoHIkTJonfnfLzUuzbkaBL.1HpA2aFBFYBH.AD.JB..A.nLlcFRlFhHi.NFPBHAHDS..A.DPPk.BHBvXT.uEiIFSlrI9fTpNZZRLYQLXF+AVoRDKNWif1LOJmvykNkY6jtFWJf83IFvzTE7x7nAkGTY2VryCsEzKCO5YISIQZ7o7M4bjw3e3fkAKtVvEXK.04FcgIiyqXdFqa53N1B+Q5RbzaCCe1afIijDmoL2fJaGAsOtmXWlGoZQVjyjHQZkzbi8ftnvtLdcpFYY4cjWFaZzGGMDWBmpL4BWECHpAb48YHCxyvlnfI0eQT74PgmVHpD+.y04BDwk1hzhE2P+59BTfzOqXszPEgdXpkdY+Ymd3B8EPdyKqEpGp3BmNAHIHfgESnqGsIi+FoqMwykNh+rvCmuQoIRSOFygMcGbhTCyN.MvWp.PZQPESk9bfbsucQVGvoVcyaG";
	}
};
}

