namespace project
{

struct TRACK_LFO_networkdata: public scriptnode::dll::InterpretedNetworkData
{
	String getId() const override
	{
		return "TRACK_LFO";
	}
	bool isModNode() const override
	{
		return false;
	}
	String getNetworkData() const override
	{
		return "1151.nT6K8Cl.Wz5H.XAYycBzxad.O5EopzledD4spWs7SP.hc+vZCKFc2sCidnqvLyQVlcO1NEvY.PF.qAPkC.tJuMVyBMcOpyQMEIQ3qbps0AHg2h39LOC9sY+6m4V2yoJoOrUCfii+1lqkJBlDVE6Sk9kVw5DbLoq6IksdwbJZG+wZFNGWwpCvwzpby9cvZPAFgtfCDa.pIvwRXQDGWxVOc+LBZx6zTmdREyuqmUulf.fWL5cUDWkY0VfDmqRVS4Y8eh0BvdlVzBrmRqbt+HqChVkWeZJV6vvWHxOZ+8ClWWgx6zsieSSuCprS6XleOzRbLpORsXy9hDYJhTtTBmiY+5Rf5mZYArAtPWck4BlLPXFqqKKLYtr4zW5ikppHNnsd84ThsUYViElqqLatpXwx0qW3yjfhOki1fGl2yZikm0igAfc0zCmNQOf8kTdfzHgZpxoGXVIEotu0H.sOHThv.DilZKTUK6ucAS3sIwHDcmZFnjYOTEMYA3GD+zCTIChL1MWBys2QT4m9fWKPGitGGNUwnmzfVn3S5VqYaMCA3YDTxestxfZFbjbqmXASEThZEX3VmTuTqZWfJs1bRdpXCGRgQeSe7VJZBtnIiFKWPHlKVr1rABgvKnklAFBpQnhHAFY..P.HADF..v3rPI7NhiDiGggiAE.CF.AHJARfAn.AR.DAPDbDF1H.21xjAJ.usEIIHli1dSJt6+tTlWDUw8i8vVqnlpc+HKtLTKT2FpdL3UTDgnZORx8beJhTqd.xUfeHHGng5HOGDjfQNG8c9qDSkYYSR64l36jx1UUWSPNpJ0iXbGstM3M23Bf9GfSgmZiy+DhH3DJlx4nxlnxcxpKn2LrIsofeJOwIaO5SLq4zmndvXRk6M+dNJR2LF4FxpklFTM5M9KMCjSRCngT9B460DpnLMnRXKUzlOerkEWKgZw6akceAq61CyphaqiMil02WaFUB9xi1GlI54upX2aUwJ.kIIpdj7h8DTPJnKxPc+x6sCAMfXdQzOnn6.QsmFxojcKiDdaYssT8cYBfXQfwz1jFVzRzt6TfFP0dWnBa4uGJ5SvVN+bUPN1uDblb7CGtIAFQsjDyPsblK.L8rmSiDr.jfNsKr2a7HEmVGyq2N7AhhvdMif0SMcoDmaLFKMZvSWPSm0VTc+S.N+eP7JcEfOQT4iLnnCHcAJPuyT8K.jGnbgioeCNetEKWHwT.fTRLMJgPP5a5wMDryYTdGYaeLPFsHgyF4EXw40dMsLFXy+uou1t2quPCZkH+fko.1TDCMONNs7PLtwmVgg7wUBRLhwtxDAiB9r5bWj7twvI5QSBVZHOz++mQmgXPoSCKfiZ4MrvYVXlYHNkgOrLh.o4y.ebNj0kHSh.YkLXpgnj8XubZAzS3vGHY0QgPVivAUg0QCXAF.EJSsxfGqY56R.SOT3i3rd9YHzoHTAZjF49riV8gs5sYZSx0Z+XMGDE6Mg0DEt6.XSdhQO0cSxm2FDG.3SBlklj3K.gdMiOFeo7FCdKOwAnYNjvtdU+93WG.";
	}
};
}

