var cs30 = ["2nd Finger", "3rd Day", "Astonished", "Bargain", "Basic", "Brew", "Bumpy", "Busy", "Bypass", "Cream", "Curious", "Devistator", "Drama", "FM Rings", "Feed Fwd", "Grizzle", "Hell Cat", "K-Legs", "K30L", "LoopG", "Maybe Strings", "Messing Around", "Pseudo Sync", "RM", "Says Things", "Screamer", "Shakey Bass", "Spl Git", "Twinkle toes", "stix"];
var em25 = ["Brass 16", "Brass 4", "Brass 8", "Organ 16", "Organ 2", "Organ 4", "Organ 8", "String 16", "String 4", "String 8"];
var sys101 = ["101-bell1", "101-bell2", "101-bell3", "101-bell4", "101-pwm1", "101-pwm2", "101-pwm3", "101-pwm4", "101-string2", "101-string3", "101-string4"];
var jx3p = ["DCO Piano", "Lfade", "Lil bass", "Round", "S&H", "Simple", "Slow One", "T Sync", "W Brass", "Wet", "harsh"];
var hybrids = ["1st", "Bell Source", "Belles", "Big", "BigElectric", "Drug Wave", "EP1", "EP2", "EP3", "Euro Organ", "GateAR", "Hard Bass", "Leap", "Lingo", "More Bell", "Odd Keys", "Rousing", "Sad Ring", "Scrd", "Simple Guitar", "Special K", "Tinkly", "eggcelent", "fat organ", "mr clicky", "mth", "nsty1", "nsty2", "pswp", "pulser", "sawd", "simr", "slowish", "swirly whirl", "walls"];
var kraftzwerg = ["BooBass", "CrazyLFO", "Gooey", "Log", "Magic Resin", "OChord", "organic"];

var Xpander = ["2 Fingers", "AV", "Another Time", "B Chord 1", "B Chord 2", "Bison 1", "Bison 2", "Boring Bass 1", "Boring Bass 2", "Bug", "E Kee 1", "E Kee 2", "Low Standards", "M Chord", "OChord", "Phase Pad", "Stack", "Thick Snappy 1", "Thick Snappy 2", "Thin Shine 1", "TubeS 1", "lose", "melomod", "osc mod", "FMThick1", "FMThick2", "FMThick3", "FMThick4", "FmDrama1", "FmDrama2"];

var Monopoly = ["2020", "Alley Cat", "Basic Lead", "Blood Organ", "Bumpkin 130", "Classy Strings", "Crab Rock", "Crab cake", "Crumb Flute", "DS", "Drink", "Fingers", "Lemon 90", "Lozange", "MP2xSaw1", "MP2xSaw3", "MP4xSaw1", "MPSawA1 ", "MPSawA2", "MPSawA3", "MPSawA4", "MPSawB1", "MPSawB2", "MPSawB3", "MPSqr-1", "MPSqr-10", "MPSqr-2", "MPSqr-3", "MPSqr-4", "MPSqr-5", "MPSqr-6", "MPSqr-7", "MPSqr-8", "MPSqr-9", "MPTri", "Not", "Rodge", "Scratchy", "Space Raider", "SyncStack", "Twisting Mellow 1", "Twisting Mellow 2", "Vibe", "consider", "funny", "heart ache", "sale"];