/** Autogenerated Main.cpp. */

// ======================| Include only the DSP files  |======================

#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// ================| Now we can add the rest of the codebase |================

#include <JuceHeader.h>

// ============================| Project Factory |============================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations ------------------------------------------------
		
		registerDataNode<project::chain3_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::Harm2_networkdata>();
		registerDataNode<project::harmonic_networkdata>();
		registerDataNode<project::main_networkdata>();
		registerDataNode<project::MainPage_networkdata>();
		registerDataNode<project::mod_networkdata>();
		registerDataNode<project::scriptnode_syntesiser1_networkdata>();
		registerDataNode<project::shaper_networkdata>();
		registerDataNode<project::synth_networkdata>();
		registerDataNode<project::_4wayswitch_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* hise::FrontendHostFactory::createStaticFactory()
{
	return new project::Factory();
}

