/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include compiled network files ------------------

#include "chain3_networkdata.h"
#include "contain_networkdata.h"
#include "files_networkdata.h"
#include "harmoG_networkdata.h"
#include "harmo_networkdata.h"
#include "main_networkdata.h"
// #include "minmax_networkdata.h"
#include "mod2_networkdata.h"
#include "mod3_networkdata.h"
#include "moddy_networkdata.h"
#include "mod_networkdata.h"
// #include "OSC.h"
#include "Q_Node_networkdata.h"
#include "s3_networkdata.h"
#include "scriptnode_syntesiser1_networkdata.h"
#include "shaper_networkdata.h"
// #include "shfilter.h"
#include "synth2_networkdata.h"
#include "synth3_networkdata.h"
#include "synth_networkdata.h"
// #include "tests_networkdata.h"
// #include "test_networkdata.h"
#include "the_networkdata.h"
#include "TRACK_LFO_networkdata.h"
#include "wdeleay_networkdata.h"
#include "weirddelay_networkdata.h"
#include "yes_midi_networkdata.h"
#include "_4wayswitch_networkdata.h"
#include "_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

