/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include compiled network files ------------------

#include "chain3_networkdata.h"
#include "Harm2_networkdata.h"
#include "harmonic_networkdata.h"
#include "MainPage_networkdata.h"
#include "main_networkdata.h"
#include "mod_networkdata.h"
#include "scriptnode_syntesiser1_networkdata.h"
#include "shaper_networkdata.h"
#include "synth_networkdata.h"
#include "_4wayswitch_networkdata.h"
#include "_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

